### ISSUE TITLE
Meine Develope geht nicht

### ISSUE THREAD

**Issue by HierGibtEsDrachen** [OctoAwesome/octoawesome#248]
Kann mir mal jemand mit der Develope helfen... 
Also ich bekommen an der stelle:
`
            simpleShader = manager.Game.Content.Load<Effect>("simple");`
Zeile 80 in der SceneControl einen Fehler.

System.Exception
  HResult=0x80131500
  Nachricht = 
  Quelle = engenious
  Stapelüberwachung:
   at engenious.Graphics.Shader.Compile()
   at engenious.Content.Serialization.EffectTypeReader.Read(ContentManager manager, ContentReader reader)
   at engenious.Content.Serialization.ContentTypeReader`1.engenious.Content.Serialization.IContentTypeReader.Read(ContentManager manager, ContentReader reader)
   at engenious.Content.ContentManager.ReadAsset[T](String assetName)
   at engenious.Content.ContentManager.Load[T](String assetName)
   at OctoAwesome.Client.Controls.SceneControl..ctor(ScreenComponent manager, String style) in C:\Users\Klaus A\Source\Repos\octoawesome\OctoAwesome\OctoAwesome.Client\Controls\SceneControl.cs:line 80
   at OctoAwesome.Client.Screens.GameScreen..ctor(ScreenComponent manager) in C:\Users\Klaus A\Source\Repos\octoawesome\OctoAwesome\OctoAwesome.Client\Screens\GameScreen.cs:line 29
 at OctoAwesome.Client.Screens.CreateUniverseScreen.<>c__DisplayClass5_0.<.ctor>b__1(Control s, MouseEventArgs e) in C:\Users\Klaus A\Source\Repos\octoawesome\OctoAwesome\OctoAwesome.Client\Screens\CreateUniverseScreen.cs:line 78
   at MonoGameUi.Control.InternalLeftMouseClick(MouseEventArgs args)
   at MonoGameUi.Control.InternalLeftMouseClick(MouseEventArgs args)
   at MonoGameUi.Control.InternalLeftMouseClick(MouseEventArgs args)
   at MonoGameUi.Control.InternalLeftMouseClick(MouseEventArgs args)
   at MonoGameUi.Control.InternalLeftMouseClick(MouseEventArgs args)
   at MonoGameUi.Control.InternalLeftMouseClick(MouseEventArgs args)
   at MonoGameUi.BaseScreenComponent.Update(GameTime gameTime)
   at engenious.Game.Update(GameTime gameTime)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseUpdateFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(Object sender, EventArgs e)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)

**Comment by HierGibtEsDrachen** [comment]
weiß nicht woran es liegt aber mit engenious 1.11 geht es.

**Comment by CsharpLassi** [comment]
Update mal Engenious auf die neueste Version und Lösche den Ordner Content im Bin Verzeichnis. Dann die Ordner bin und obj im Ordner Content von Octoawesome.Client, wenn da eine engenious.Content.*.dll ist auch die.

Dann musst du das Contenttool öffnen und die ecb datei im Content-Ordner von Octoawesome.Client öffnen und neu speichern.

Das Contenttool findest du im ordner packages.

Das sollte helfen

**Comment by CsharpLassi** [comment]
Das Problem ist es hat sich einiges getan an den Shadern und das nicht unbedingt abwärts kompatibel.

**Comment by HierGibtEsDrachen** [comment]
Meinst du engenious.CreatedContent.Content.dll?
Naja mit der neusten Version gehen meine Buttons nicht mehr.

**Comment by HierGibtEsDrachen** [comment]
#246  hier steht die Benutzte Hardware.
Also wenn es an der Hardware liegt das die UI Element nicht gehen, dann muss ich wohl wechseln.
Hat sonst noch wer das Problem gehabt?

**Comment by jvbsl** [comment]
Betriebssystem? Mal probiert das fenster an den ganz linken oberen Rand deines screens zu verschieben um zu gucken, ob du die buttons dann zum reagieren bekommst?

**Comment by Gallimathias** [comment]
Hast du den scho die dll bzw. den ordner gelöscht so wie @CsharpLassi gesagt hat. bei uns gibts hin und wieder im stream auch mal probleme wenn wir einen branch wechseln bzw. etwas neu vom repo holen.

**Comment by HierGibtEsDrachen** [comment]
Ja hab alles gelöscht und neu erstellt.
@jvbsl  Windows 10 64 Bit.
Fullscreen und Fenster ganz links geht auch nicht.

**Comment by jvbsl** [comment]
das müsst ich mal entsprechend auf der Hardware debuggen, oder du könntest es auch machen ist ja OS

**Comment by jvbsl** [comment]
achja tritt der Fehler aus dem ersten Post überhaupt noch zu? Ansonsten:
> Wenn du genaueres wissen willst führ das ContentTool manuell aus und schau die Fehlermeldung dort an, wenn es dort keine gibt, läuft irgendetwas mächtig schief.
Welche OpenGL Version hast du denn? OpenGL 1.1 ist zu alt

**Comment by HierGibtEsDrachen** [comment]
Das hab ich wie gesagt schon gemacht :)
hab es hinbekommen fahr jetzt mit 1.12^^

**Comment by jvbsl** [comment]
Wär dir trotzdem sehr verbunden, wenn du das mit der höheren Version mal debuggen könntest, denn die einzige Erklärung die ich aktuell hätte wäre wenn SDL statt WinAPI benutzt wird, denn in OpenGL 2.0 ist da aktuell noch ein Fehler(korrigiert haben sie es schon, nur noch nicht gemergt).

**Comment by HierGibtEsDrachen** [comment]
Hmm ja, aber müsste ich dazu nicht die MonogameUI.dll debuggen weiß grad nicht wo ich da rein schauen sollte bei engenious... 
Auf jeden Fall sieht es so aus mit engenious 1.28 die Hitboxen der Buttons auf dem MainScreen verschieben sich immer wenn man aus dem Fenster tabt ... und sind immer wo anders auch beim Start.
Der Selected Indicator (gestrichelte Linie) ist aber um den Button herum gezeichnet. Sehr sehr komisch.
![buttonshift1](https://user-images.githubusercontent.com/36693858/37007804-7fc0da96-20df-11e8-86a0-8c1ee470fa19.png)
![buttonshift2](https://user-images.githubusercontent.com/36693858/37007808-7fe9f02a-20df-11e8-9384-327be25fecc9.png)
hab sie zweimal gesucht. Ist rot eingezeichnet.
Wenn du mir kurz erklären könntest wo ich beim Debuggen rein müsst, oder wie ich das machen soll schau ich es mir mal an. Habs nicht geschaft die MonogameUI /feature/engenious zu bauen da fehlt die package info und manuell hab ich es nicht hingekriegt. welcher Branch bei engenious ist den 1.28?

**Comment by jvbsl** [comment]
Hört sich für mich nach dem hier an...
https://github.com/OctoAwesome/engenious/issues/50

Sollte also bug von OpenTK sein. Denke musst also nicht debuggen.
develop branch ist quasi nightly build. Master wird dann 1.0.0

**Comment by HierGibtEsDrachen** [comment]
hätte da noch eine frage wo ist denn der unterschied von engeniousUI zu der monogameUI die in OctoAwesem verwendet wird ?

**Comment by ManuelHu** [comment]
EngeniousUi war ein Versuch, MonoGameUi mit Abhängigkeiten zu engenious als NuGet-Paket bereitzustellen. Mittlerweile ist dieses Projekt aber eingeschlafen. Fixes für die neuesten engenious-Versionen und all+gemein Bugfixes/weiterenwicklungen hat nur noch der Branch feature/engenious bei monogameui.

**Comment by Gallimathias** [comment]
Ich denke das sich das erledigt hat. Wenn es noch Probleme gibt einfach ein neues Issue aufmachen.
